In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

/home/siavash/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/siavash/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/siavash/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [5]:
from sklearn.datasets import load_iris

In [6]:
X, y = load_iris(return_X_y=True)

In [7]:
X.shape

(150, 4)

In [8]:
y.size

150

In [9]:
from sklearn.model_selection import cross_val_score, cross_val_predict

#### LogisticRegression

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
LogisticRegression?

In [12]:
lr= LogisticRegression()

In [13]:
cross_val_score(lr,X ,y, cv=5)

/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_mod

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [14]:
cross_val_score(lr,X ,y, cv=5).mean()

/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_mod

0.9600000000000002

In [15]:
y_hat= cross_val_predict(lr, X ,y, cv=5)
y_hat

/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/siavash/anaconda3/lib/python3.7/site-packages/sklearn/linear_mod

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [17]:
print(accuracy_score(y, y_hat))

0.96


In [18]:
print(confusion_matrix(y, y_hat))

[[50  0  0]
 [ 0 45  5]
 [ 0  1 49]]


In [19]:
print(classification_report(y, y_hat))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.98      0.90      0.94        50
           2       0.91      0.98      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150



#### KNeighborsClassifier

In [20]:
from sklearn.neighbors import KNeighborsClassifier

/home/siavash/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [21]:
knn= KNeighborsClassifier(n_neighbors=5)

In [22]:
cross_val_score(knn,X ,y, cv=5)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [23]:
y_hat= cross_val_predict(knn,X ,y, cv=5)

In [24]:
print(accuracy_score(y, y_hat))

0.9733333333333334


#### DecisionTreeClassifier

In [28]:
from sklearn.tree import DecisionTreeClassifier

/home/siavash/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [29]:
dtc= DecisionTreeClassifier()

In [30]:
cross_val_score(dtc,X ,y, cv=5).mean()

0.9600000000000002

#### RandomForestClassifier

In [31]:
from sklearn.ensemble import RandomForestClassifier

/home/siavash/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [32]:
rfc= RandomForestClassifier(n_estimators=100)

In [33]:
cross_val_score(rfc,X ,y, cv=5).mean()

0.96

#### Support Vector Machines

In [34]:
from sklearn.svm import SVC

In [67]:
svc= SVC(kernel='linear')

In [68]:
cross_val_score(svc,X,y,cv=5).mean()

0.9800000000000001

#### Support Vector Machines "Linear"

In [70]:
from sklearn.svm import LinearSVC

In [76]:
cross_val_score(LinearSVC(max_iter=10000),X,y,cv=5).mean()

0.9666666666666668

In [85]:
from sklearn.model_selection import ShuffleSplit

ShuffleSplit?

In [100]:
lst= [10*x for x in range(1,17)]

In [101]:
lst

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160]

In [103]:
rs= ShuffleSplit(n_splits=4,test_size=0.25)

In [106]:
cross_val_score(svc,X,y,cv=rs)

array([0.97368421, 1.        , 0.94736842, 1.        ])

In [110]:
for train,test in rs.split(lst):
    print(f'TRAIN: {train}\nTEST: {test}\n')

TRAIN: [12 10  2 11  4 14  7  6  1 13  8  0]
TEST: [ 5  9 15  3]

TRAIN: [14  2  3  9 15  8  6  5 13  7  1 10]
TEST: [12  0  4 11]

TRAIN: [ 1  7  9 12  8 15 11  3  4 13  0  6]
TEST: [10  2 14  5]

TRAIN: [ 9  1 12 10 13  5  8  2  4  3 11  6]
TEST: [15 14  7  0]



In [107]:
from sklearn.model_selection import train_test_split

In [111]:
from sklearn.model_selection import KFold

KFold?

In [122]:
# one random train-test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
svc.fit(X_train,y_train)
svc.score(X_test,y_test)

0.9777777777777777

In [124]:
# n random train-test set
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
cv= ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
score= cross_val_score(svc, X,y, cv=cv)
print(score)
print(score.mean())

[0.97777778 0.97777778 1.         0.95555556 1.        ]
0.9822222222222223


In [174]:
# cross validation ( cv is by default: "(Stratified)KFold" )
from sklearn.model_selection import cross_val_score,cross_val_predict
y_hat= cross_val_predict(svc, X,y, cv=10)
score= cross_val_score(svc, X,y, cv=10)
print(score)
print(score.mean())

[1.         0.93333333 1.         1.         0.86666667 1.
 0.93333333 1.         1.         1.        ]
0.9733333333333334


In [179]:
# K Fold
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score,cross_val_predict
kf = KFold(n_splits=4,shuffle=True)
score= cross_val_score(svc, X,y, cv=kf)
print(score)
print(score.mean())
# kf.split(X) # indexes in train and test set

[0.94736842 0.97368421 1.         1.        ]
0.9802631578947368


In [180]:
# Stratified K Fold (evenly distrubted traget class in train and test sets)
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score,cross_val_predict
skf= StratifiedKFold(n_splits=4,shuffle=True)
score= cross_val_score(svc, X,y, cv=skf)
print(score)
print(score.mean())
# skf.split(X,y) # indexes in train and test set

[0.97435897 1.         0.97222222 1.        ]
0.9866452991452992


In [163]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4,shuffle=True)
kf.split(lst)

<generator object _BaseKFold.split at 0x7f11b5fe2ed0>

In [164]:
for train,test in kf.split(lst):
    print(f'TRAIN: {train}\nTEST: {test}\n')

TRAIN: [ 1  2  3  5  6  7  8  9 10 12 13 14]
TEST: [ 0  4 11 15]

TRAIN: [ 0  1  2  3  4  6  9 11 12 13 14 15]
TEST: [ 5  7  8 10]

TRAIN: [ 0  1  2  4  5  6  7  8 10 11 14 15]
TEST: [ 3  9 12 13]

TRAIN: [ 0  3  4  5  7  8  9 10 11 12 13 15]
TEST: [ 1  2  6 14]



In [165]:
tgt= 12*[0] + 4*[1]
tgt

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]

In [166]:
from sklearn.model_selection import StratifiedKFold
skf= StratifiedKFold(n_splits=4,shuffle=True)
skf.split(lst,tgt)

<generator object _BaseKFold.split at 0x7f11b5fe2840>

In [167]:
for train,test in skf.split(lst,tgt):
    print(f'TRAIN: {train}\nTEST: {test}\n')

TRAIN: [ 0  1  2  3  5  6  8  9 10 12 14 15]
TEST: [ 4  7 11 13]

TRAIN: [ 0  4  5  6  7  8  9 10 11 12 13 14]
TEST: [ 1  2  3 15]

TRAIN: [ 1  2  3  4  5  6  7  9 11 13 14 15]
TEST: [ 0  8 10 12]

TRAIN: [ 0  1  2  3  4  7  8 10 11 12 13 15]
TEST: [ 5  6  9 14]



In [170]:
cross_val_score(svc,X,y,cv=skf)

array([1.        , 0.97435897, 1.        , 0.97222222])

### Timeseries split

In [181]:
from sklearn.model_selection import TimeSeriesSplit

In [211]:
ts= TimeSeriesSplit(n_splits=4)

In [ ]:
# cross_val_score(estimator,X,y,cv=ts)

In [213]:
ts.split(X)

<generator object TimeSeriesSplit.split at 0x7f11b6018138>

In [216]:
for train,test in ts.split(lst):
    print(f'TRAIN: {train}\nTEST: {test}\n')

TRAIN: [0 1 2 3 4 5]
TEST: [ 6  7  8  9 10]

TRAIN: [ 0  1  2  3  4  5  6  7  8  9 10]
TEST: [11 12 13 14 15]

